"""update

Revision ID: 1eb260867618
Revises: 40f28047ba8b
Create Date: 2017-08-24 15:39:47.313115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb260867618'
down_revision = '40f28047ba8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('T_Workflow_Journals', sa.Column('operator_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('T_Workflow_Journals', 'operator_name')
    # ### end Alembic commands ###
