"""add the workflow journal

Revision ID: 4093a2801b70
Revises: aeaf7486e25f
Create Date: 2017-08-21 18:14:05.418284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4093a2801b70'
down_revision = 'aeaf7486e25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_AfterService_Workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=14), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('customer', sa.String(length=20), nullable=True),
    sa.Column('material_number', sa.String(length=20), nullable=True),
    sa.Column('saler_name', sa.String(length=20), nullable=True),
    sa.Column('expired_status', sa.String(length=20), nullable=True),
    sa.Column('summited_at', sa.DateTime(), nullable=True),
    sa.Column('material_supplier', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('workflow_status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('T_Workflow_Journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('destination', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Waixies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Waixies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=14), nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('customer', sa.VARCHAR(length=20), nullable=True),
    sa.Column('material_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('saler_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('expired_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('summited_at', sa.DATETIME(), nullable=True),
    sa.Column('material_supplier', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.drop_table('T_Workflow_Journals')
    op.drop_table('T_AfterService_Workflow')
    # ### end Alembic commands ###
