"""init

Revision ID: 40f28047ba8b
Revises: 
Create Date: 2017-08-24 11:41:31.581308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f28047ba8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_AfterService_Workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=14), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('expired_status', sa.String(length=100), nullable=True),
    sa.Column('summited_at', sa.DateTime(), nullable=True),
    sa.Column('material_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('workflow_status', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('material_supplier_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('creater_id', sa.Integer(), nullable=True),
    sa.Column('saler_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('T_PRT_AllProduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemName', sa.String(), nullable=True),
    sa.Column('skuCode', sa.String(), nullable=True),
    sa.Column('itemCode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('T_PRT_SupplierBasicInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplierName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('T_SYS_User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(), nullable=True),
    sa.Column('dptNames', sa.String(), nullable=True),
    sa.Column('dptIds', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('T_PRT_AbnormalProduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skuCode', sa.String(length=100), nullable=True),
    sa.Column('waixieid', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['waixieid'], ['T_AfterService_Workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('T_Workflow_Journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('workflow_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('destination', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['T_AfterService_Workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_Workflow_Journals')
    op.drop_table('T_PRT_AbnormalProduct')
    op.drop_table('T_SYS_User')
    op.drop_table('T_PRT_SupplierBasicInfo')
    op.drop_table('T_PRT_AllProduct')
    op.drop_table('T_AfterService_Workflows')
    # ### end Alembic commands ###
