"""initial migration

Revision ID: aeaf7486e25f
Revises: 
Create Date: 2017-08-15 16:22:10.963594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeaf7486e25f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Waixies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=14), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('customer', sa.String(length=20), nullable=True),
    sa.Column('material_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('saler_name', sa.String(length=20), nullable=True),
    sa.Column('expired_status', sa.String(length=20), nullable=True),
    sa.Column('summited_at', sa.DateTime(), nullable=True),
    sa.Column('material_supplier', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Waixies')
    # ### end Alembic commands ###
