"""init

Revision ID: f5dc842abec0
Revises: 
Create Date: 2017-08-23 09:50:06.640053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5dc842abec0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_AfterService_Workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=14), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('customer_guid', sa.String(length=20), nullable=True),
    sa.Column('creater_guid', sa.String(length=20), nullable=True),
    sa.Column('saler_name', sa.String(length=20), nullable=True),
    sa.Column('expired_status', sa.String(length=20), nullable=True),
    sa.Column('summited_at', sa.DateTime(), nullable=True),
    sa.Column('material_number', sa.String(length=20), nullable=True),
    sa.Column('material_supplier_guid', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('workflow_status', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('T_Workflow_Journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('workflow_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('destination', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_Workflow_Journals')
    op.drop_table('T_AfterService_Workflows')
    # ### end Alembic commands ###
